# Generated by Django 2.1.2 on 2018-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='This is my app', max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
